config/routes.rb
Citecount::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :citations

  resources :articles do
    get 'page/:page', :action => :index, :on => :collection
  end
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :citations
  attr_accessible :author, :journal, :reference_type, :title, :year
end

app/models/citation.rb
class Citation < ActiveRecord::Base
  belongs_to :article
  belongs_to :cite, :class_name => "Article"
  attr_accessible :article_id, :cite_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'numbers_in_words'
  require 'numbers_in_words/duck_punch'
  # GET /articles
  # GET /articles.json
  def index
    # get the source articles
    @total = Article.where(:reference_type => "source").count
    @art = Article.order("journal").where(:reference_type => "source").page(params[:page]).per(25)
    @articles = {}
    # create a hash of citation articles for each source article
    @art.each do |a|
      if @articles.has_key?(a.journal) == false
        @articles[a.journal] = {} 
        @articles[a.journal][:count] = 0
      end
      @articles[a.journal][:count] += 1
      # find all the citation articles for this article
      citation = Article.find(:all, :conditions=> {:id => a.citation_ids, :reference_type => 'citation'})

      # looping over the list of citations for this article
      citation.each do |c|
        if c.journal.blank? == false
          if @articles[a.journal].has_key?(c.journal) == false
            @articles[a.journal][c.journal] = 0
          end
          @articles[a.journal][c.journal] += 1
        end
      end
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  # GET /citations
  # GET /citations.json
  def index
    #@citations = Citation.all
    @citations = Article.order("journal").where(:reference_type => 'citation')
    @journals = {}
    @citations.each do |c|
      if not @journals.has_key?(c.journal)
        @journals[c.journal] = 0
      end
      @journals[c.journal] += 1
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @citations }
    end
  end

  # GET /citations/1
  # GET /citations/1.json
  def show
    @citation = Citation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @citation }
    end
  end

  # GET /citations/new
  # GET /citations/new.json
  def new
    @citation = Citation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @citation }
    end
  end

  # GET /citations/1/edit
  def edit
    @citation = Citation.find(params[:id])
  end

  # POST /citations
  # POST /citations.json
  def create
    @citation = Citation.new(params[:citation])

    respond_to do |format|
      if @citation.save
        format.html { redirect_to @citation, notice: 'Citation was successfully created.' }
        format.json { render json: @citation, status: :created, location: @citation }
      else
        format.html { render action: "new" }
        format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /citations/1
  # PUT /citations/1.json
  def update
    @citation = Citation.find(params[:id])

    respond_to do |format|
      if @citation.update_attributes(params[:citation])
        format.html { redirect_to @citation, notice: 'Citation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @citation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citations/1
  # DELETE /citations/1.json
  def destroy
    @citation = Citation.find(params[:id])
    @citation.destroy

    respond_to do |format|
      format.html { redirect_to citations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :journal %><br />
    <%= f.text_field :journal %>
  </div>
  <div class="field">
    <%= f.label :reference_type %><br />
    <%= f.text_field :reference_type %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<p>
Listing the names of Journals that have been published, the number in parens indicates the number of articles published in that journal.
If you click on the Journal name you will see a listing of cited journals from the article(s) published in the journal.
</p>
<%= paginate @art %>
<div class="accordion" id="accordion1">
  <% @articles.each_with_index do |(key, value), index| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-present="#accordion<%= index %>" href="#collapse<%= index.in_words %>"><%= index+1 %>) <%= key.titleize %> (<%= value[:count] %>)</a>
    </div>
    <div id="collapse<%= index.in_words %>" class="accordion-body collapse">
      <div class="accordion-inner">
      <% value = value.delete_if { |k| k.to_s.match(/count/) } %>
      <% value.sort_by{ |ke,va| ke}.each do |v,count| %>
      <%# value.each do |v,count| %>
        <% if not v.blank? %><%= v.titleize %> (<%= count %>)<br /><% end %>
      <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br />
<%= paginate @art %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Journal:</b>
  <%= @article.journal %>
</p>

<p>
  <b>Reference type:</b>
  <%= @article.reference_type %>
</p>

<p>
  <b>Author:</b>
  <%= @article.author %>
</p>

<p>
  <b>Year:</b>
  <%= @article.year %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/citations/_form.html.erb
<%= form_for(@citation) do |f| %>
  <% if @citation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@citation.errors.count, "error") %> prohibited this citation from being saved:</h2>

      <ul>
      <% @citation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :cite_id %><br />
    <%= f.number_field :cite_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/citations/edit.html.erb
<h1>Editing citation</h1>

<%= render 'form' %>

<%= link_to 'Show', @citation %> |
<%= link_to 'Back', citations_path %>

app/views/citations/index.html.erb
<h1>Citations</h1>
<p>
<%= @citations.size %> cited journals in 500 source articles.  The % given next to the number cited is
the percent of times out of 500 source articles this journal was used.  So number of times cited/500.
</p>
<table class="table table-striped table-hover">
  <tr>
    <th>Journal</th>
    <th>Cited</th>
  </tr>

<% @journals.each do |journal, count| %>
  <tr>
    <td><%= journal %></td>
    <td><%= count %> (<%= number_to_percentage(count.to_f/500.0) %>)</td> 
  </tr>
<% end %>
</table>

app/views/citations/new.html.erb
<h1>New citation</h1>

<%= render 'form' %>

<%= link_to 'Back', citations_path %>

app/views/citations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @citation.article_id %>
</p>

<p>
  <b>Cite:</b>
  <%= @citation.cite_id %>
</p>


<%= link_to 'Edit', edit_citation_path(@citation) %> |
<%= link_to 'Back', citations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Citecount</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, intial-scale=1.0">
</head>
<body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Citecount</a>
          <div class="nav-collapse collapse">
<!--
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
-->
            <ul class="nav">
              <li <% if params[:controller] == "articles" %>class="active"<% end %>><a href="/articles">Articles</a></li>
              <li <% if params[:controller] == "citations" %>class="active"<% end %>><a href="/citations">Citations</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

  <div class="container-fluid">
    <div class="row-fluid">
<%= yield %>
    </div>
    <hr>
      <footer>
        <p>&copy;2013</p>
      </footer>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>